apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: porodnica-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: porodnica-webapi-config
    literals:
      - database=porodnica-ambulance-home
      - collection=porodnica
patches:
- path: patches/webapi.deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: porodnica-webapi